# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8322e6c3fc6ee3b65cb136d2c8b17d11e9990f562cd6c2469da799e574fc773a379500c2089fb0ca9ed0ec41f410e44af2fbbbac3c1cf698dfda71b63a67f6be

test:
  secret_key_base: 2b2feb9a71192e198efbfa8ba31915bf0a5b7a67d782b6020c059c46429474c7d58d0bc2ba6b6eae74fce4801c89865fd8d13dff9f8e0c488e5beb3f4639b19d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
